#!/usr/bin/env bash

if which systemctl > /dev/null; then
  echo "Starting docker"
  systemctl start docker
  sleep 5
fi

echo "Pruning dangling images"
docker images -f dangling=true | awk '{print $3}' | xargs docker rmi || true

echo "Pruning unused gliderlabs/herokuish images"
docker images -a | grep "^gliderlabs\/herokuish" | grep -v latest | awk '{print $3}' | xargs docker rmi || true

echo 'Importing herokuish into docker (around 5 minutes)'
if [[ -n "$http_proxy" ]] || [[ -n "$https_proxy" ]]; then
  echo "See the docker pull docs for proxy configuration";
fi

VERSION=$(cat /var/lib/herokuish/VERSION)

sudo docker pull "gliderlabs/herokuish:v${VERSION}-18"
sudo docker pull "gliderlabs/herokuish:v${VERSION}-20"
sudo docker pull "gliderlabs/herokuish:v${VERSION}-22"
sudo docker tag "gliderlabs/herokuish:v${VERSION}-18" gliderlabs/herokuish:latest
sudo docker tag "gliderlabs/herokuish:v${VERSION}-20" gliderlabs/herokuish:latest-20
sudo docker tag "gliderlabs/herokuish:v${VERSION}-22" gliderlabs/herokuish:latest-22
