linters:
  shellcheck:
    shell: bash
    exclude: 'SC2002,SC2030,SC2031,SC2034'
  golint:
ignore:
  files:
    - 'vendor/*'
    - 'bower_components/*'
    - 'node_modules/*'
    - 'buildpacks/*/tests/*/test.sh'
