FROM heroku/heroku:16-build

ENV DEBIAN_FRONTEND noninteractive

COPY ./build/linux/herokuish /bin/herokuish
RUN /bin/herokuish buildpack install \
	&& ln -s /bin/herokuish /build \
	&& ln -s /bin/herokuish /start \
	&& ln -s /bin/herokuish /exec
COPY include/default_user.bash /tmp/default_user.bash
RUN bash /tmp/default_user.bash && rm -f /tmp/default_user.bash
